name: Download and patch game files
on: [push]

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - uses: "Kesefon/steamfetch-action@master"
      with:
        username: "${{ secrets.STEAM_USER }}"
        password: "${{ secrets.STEAM_PASS }}"
        dir: "${{ github.workspace }}/game_files/"
        os: "windows"
        app: 1454400
        osarch: 64
        files: |
          resources/app/preload.js
          resources/app/start.js
          resources/app/package.json
    - run: patch -d $GITHUB_WORKSPACE/game_files/resources/app/ --binary -p1 -i $GITHUB_WORKSPACE/patch.diff
    - run: cp $GITHUB_WORKSPACE/game_files/resources/app/* $GITHUB_WORKSPACE/
    - run: npm install
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: patchedFiles
        path: |
          preload.js
          start.js
          package.json
          mods/
          discordRPC.js
          node_modules/
          !node_modules/steamapi/
